language: python
sudo: false
dist: bionic
cache:
  pip: true
  directories:
  - eggs
  - downloads
services:
  - elasticsearch
  - redis:wq
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=51
  include:
    - python: "3.7"
      env: PLONE_VERSION=52
  fast_finish: true
before_install:
  - ln -s test_plone$PLONE_VERSION.cfg buildout.cfg

install:
  - pip install -r requirements.txt -c constraints_plone$PLONE_VERSION.txt
  - buildout -N -t 3 code-analysis:return-status-codes=True annotate
  - buildout -N -t 3 code-analysis:return-status-codes=True

script:
# Run code-analysis, except on Python 3.6, which mysteriously fails to find zc.buildout.
  - python --version 2> /dev/stdout | grep 3.6 || bin/code-analysis
  - bin/test --all

after_success:
  - bin/createcoverage --output-dir=parts/test/coverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - bin/pip install -q coveralls
  - coveralls
